import { readFileSync, writeFileSync } from 'fs';

const todas = JSON.parse(readFileSync('./src/data/clasicos.json', 'utf-8'));
const existentesSet = new Set(todas.map(c => `${c.titulo.toLowerCase()}|${c.artista.toLowerCase()}`));

function agregar(titulo, artista, year, genero) {
  const key = `${titulo.toLowerCase()}|${artista.toLowerCase()}`;
  if (existentesSet.has(key)) return;
  existentesSet.add(key);
  todas.push({ id: "", titulo, artista, year, genero });
}

// TROPICAL (31 -> 60, necesito 29)
agregar("Quimbara", "Celia Cruz", 1974, "Tropical");
agregar("Bemba Colorá", "Celia Cruz", 1966, "Tropical");
agregar("Tu Con Tu", "Frank Reyes", 2003, "Tropical");
agregar("Ahora Me Llama", "Karol G & Bad Bunny", 2017, "Tropical");
agregar("Propuesta Indecente", "Romeo Santos", 2013, "Tropical");
agregar("Eres Mía", "Romeo Santos", 2014, "Tropical");
agregar("Darte Un Beso", "Prince Royce", 2013, "Tropical");
agregar("Corazón Sin Cara", "Prince Royce", 2010, "Tropical");
agregar("Stand By Me", "Prince Royce", 2010, "Tropical");
agregar("El Perdón", "Nicky Jam & Enrique Iglesias", 2015, "Tropical");
agregar("Yo No Sé Mañana", "Luis Enrique", 1991, "Tropical");
agregar("Quiero Ser Tu Sombra", "Frankie Ruiz", 1985, "Tropical");
agregar("La Cura", "Frankie Ruiz", 1986, "Tropical");
agregar("Idilio", "Willie Colón", 1981, "Tropical");
agregar("Periódico De Ayer", "Héctor Lavoe", 1976, "Tropical");
agregar("Mi Gente", "Héctor Lavoe", 1975, "Tropical");
agregar("Juanito Alimaña", "Héctor Lavoe", 1983, "Tropical");
agregar("Quimbara", "Celia Cruz", 1974, "Tropical");
agregar("A Pedir Su Mano", "Juan Luis Guerra", 1990, "Tropical");
agregar("Visa Para Un Sueño", "Juan Luis Guerra", 1990, "Tropical");
agregar("La Bilirrubina", "Juan Luis Guerra", 1990, "Tropical");
agregar("Burbujas De Amor", "Juan Luis Guerra", 1990, "Tropical");
agregar("Rebelión", "Joe Arroyo", 1986, "Tropical");
agregar("En Barranquilla Me Quedo", "Joe Arroyo", 1988, "Tropical");
agregar("La Noche", "Joe Arroyo", 1986, "Tropical");
agregar("Ese Hombre", "Pimpinela", 1986, "Tropical");
agregar("Llorarás", "Óscar de León", 1975, "Tropical");
agregar("Taboga", "Rubén Blades", 1988, "Tropical");
agregar("Plástico", "Rubén Blades", 1978, "Tropical");

// CLASICOS LATINOS (25 -> 60, necesito 35)
agregar("Perfidia", "Los Panchos", 1940, "Clásicos Latinos");
agregar("Quizás Quizás Quizás", "Nat King Cole", 1958, "Clásicos Latinos");
agregar("Contigo En La Distancia", "Luis Miguel", 1991, "Clásicos Latinos");
agregar("La Puerta", "Los Panchos", 1952, "Clásicos Latinos");
agregar("Reloj No Marques Las Horas", "Los Panchos", 1956, "Clásicos Latinos");
agregar("Piel Canela", "Los Panchos", 1953, "Clásicos Latinos");
agregar("Cómo Fue", "Benny Moré", 1953, "Clásicos Latinos");
agregar("Dos Gardenias", "Ibrahim Ferrer", 1999, "Clásicos Latinos");
agregar("Chan Chan", "Buena Vista Social Club", 1997, "Clásicos Latinos");
agregar("El Cuarto De Tula", "Buena Vista Social Club", 1997, "Clásicos Latinos");
agregar("Guantanamera", "Celia Cruz", 1967, "Clásicos Latinos");
agregar("Angelitos Negros", "Antonio Machín", 1950, "Clásicos Latinos");
agregar("Amapola", "Nana Mouskouri", 1924, "Clásicos Latinos");
agregar("María Elena", "Los Indios Tabajaras", 1936, "Clásicos Latinos");
agregar("Nosotros", "Los Panchos", 1943, "Clásicos Latinos");
agregar("La Copa Rota", "José Feliciano", 1968, "Clásicos Latinos");
agregar("Soy Lo Prohibido", "Olga Guillot", 1957, "Clásicos Latinos");
agregar("Adoro", "Armando Manzanero", 1967, "Clásicos Latinos");
agregar("Contigo Aprendí", "Armando Manzanero", 1967, "Clásicos Latinos");
agregar("No Sé Tú", "Luis Miguel", 1992, "Clásicos Latinos");
agregar("La Media Vuelta", "Luis Miguel", 1991, "Clásicos Latinos");
agregar("Solamente Una Vez", "Luis Miguel", 1991, "Clásicos Latinos");
agregar("Amor Eterno", "Rocío Dúrcal", 1984, "Clásicos Latinos");
agregar("Fallaste Corazón", "Pedro Infante", 1951, "Clásicos Latinos");
agregar("Cien Años", "Pedro Infante", 1954, "Clásicos Latinos");
agregar("Amorcito Corazón", "Pedro Infante", 1953, "Clásicos Latinos");
agregar("Adiós Muchachos", "Carlos Gardel", 1929, "Clásicos Latinos");
agregar("El Día Que Me Quieras", "Carlos Gardel", 1935, "Clásicos Latinos");
agregar("Mi Buenos Aires Querido", "Carlos Gardel", 1934, "Clásicos Latinos");
agregar("Por Una Cabeza", "Carlos Gardel", 1935, "Clásicos Latinos");
agregar("Caminito", "Carlos Gardel", 1926, "Clásicos Latinos");
agregar("Nostalgias", "Carlos Gardel", 1936, "Clásicos Latinos");
agregar("La Cumparsita", "Carlos Gardel", 1917, "Clásicos Latinos");
agregar("Alma Llanera", "Pedro Rafael Gutiérrez", 1914, "Clásicos Latinos");
agregar("Moliendo Café", "Hugo Blanco", 1961, "Clásicos Latinos");

// TROVA/CANTAUTOR (17 -> 60, necesito 43)
agregar("Ojalá", "Silvio Rodríguez", 1978, "Trova/Cantautor");
agregar("Unicornio", "Silvio Rodríguez", 1982, "Trova/Cantautor");
agregar("Te Doy Una Canción", "Silvio Rodríguez", 1978, "Trova/Cantautor");
agregar("La Maza", "Silvio Rodríguez", 1982, "Trova/Cantautor");
agregar("El Necio", "Silvio Rodríguez", 1992, "Trova/Cantautor");
agregar("Quién Fuera", "Silvio Rodríguez", 1978, "Trova/Cantautor");
agregar("Yo Pisaré Las Calles Nuevamente", "Pablo Milanés", 1975, "Trova/Cantautor");
agregar("El Breve Espacio En Que No Estás", "Pablo Milanés", 1978, "Trova/Cantautor");
agregar("Años", "Pablo Milanés", 1980, "Trova/Cantautor");
agregar("Para Vivir", "Pablo Milanés", 1974, "Trova/Cantautor");
agregar("Te Recuerdo Amanda", "Víctor Jara", 1969, "Trova/Cantautor");
agregar("El Derecho De Vivir En Paz", "Víctor Jara", 1971, "Trova/Cantautor");
agregar("Plegaria A Un Labrador", "Víctor Jara", 1969, "Trova/Cantautor");
agregar("Manifiesto", "Víctor Jara", 1973, "Trova/Cantautor");
agregar("Luchin", "Víctor Jara", 1974, "Trova/Cantautor");
agregar("Todo Cambia", "Mercedes Sosa", 1984, "Trova/Cantautor");
agregar("Sólo Le Pido A Dios", "Mercedes Sosa", 1978, "Trova/Cantautor");
agregar("Canción Con Todos", "Mercedes Sosa", 1969, "Trova/Cantautor");
agregar("Duerme Negrito", "Mercedes Sosa", 1970, "Trova/Cantautor");
agregar("Volver A Los 17", "Violeta Parra", 1966, "Trova/Cantautor");
agregar("Run Run Se Fue Pa'l Norte", "Violeta Parra", 1966, "Trova/Cantautor");
agregar("La Jardinera", "Violeta Parra", 1953, "Trova/Cantautor");
agregar("Maldigo Del Alto Cielo", "Violeta Parra", 1966, "Trova/Cantautor");
agregar("Rin Del Angelito", "Violeta Parra", 1966, "Trova/Cantautor");
agregar("Construcción", "Chico Buarque", 1971, "Trova/Cantautor");
agregar("A Pesar De Usted", "Chico Buarque", 1970, "Trova/Cantautor");
agregar("Cálice", "Chico Buarque", 1973, "Trova/Cantautor");
agregar("Inconsciente Colectivo", "Charly García", 1982, "Trova/Cantautor");
agregar("Canción Para Mi Muerte", "Sui Generis", 1972, "Trova/Cantautor");
agregar("Confesiones De Invierno", "Sui Generis", 1973, "Trova/Cantautor");
agregar("Contaminame", "Pedro Guerra", 1995, "Trova/Cantautor");
agregar("Y Sin Embargo", "Joaquín Sabina", 1996, "Trova/Cantautor");
agregar("Calle Melancolía", "Joaquín Sabina", 1980, "Trova/Cantautor");
agregar("Princesa", "Joaquín Sabina", 1985, "Trova/Cantautor");
agregar("Quién Me Ha Robado El Mes De Abril", "Joaquín Sabina", 1988, "Trova/Cantautor");
agregar("Pasacalle", "Facundo Cabral", 1970, "Trova/Cantautor");
agregar("No Soy De Aquí Ni Soy De Allá", "Facundo Cabral", 1970, "Trova/Cantautor");
agregar("Pobrecito Mi Patrón", "Facundo Cabral", 1972, "Trova/Cantautor");
agregar("Sueño Con Serpientes", "Silvio Rodríguez", 1975, "Trova/Cantautor");
agregar("Como La Cigarra", "María Elena Walsh", 1972, "Trova/Cantautor");
agregar("Serenata Para La Tierra De Uno", "María Elena Walsh", 1976, "Trova/Cantautor");
agregar("Drume Negrita", "Bola de Nieve", 1945, "Trova/Cantautor");
agregar("La Era Está Pariendo Un Corazón", "Silvio Rodríguez", 1978, "Trova/Cantautor");

// RANCHERA (14 -> 60, necesito 46)
agregar("Volver Volver", "Vicente Fernández", 1972, "Ranchera");
agregar("Por Tu Maldito Amor", "Vicente Fernández", 1989, "Ranchera");
agregar("Lástima Que Seas Ajena", "Vicente Fernández", 1993, "Ranchera");
agregar("Mujeres Divinas", "Vicente Fernández", 1985, "Ranchera");
agregar("Estos Celos", "Vicente Fernández", 2007, "Ranchera");
agregar("De Qué Manera Te Olvido", "Vicente Fernández", 1987, "Ranchera");
agregar("Acá Entre Nos", "Vicente Fernández", 1987, "Ranchera");
agregar("Hermoso Cariño", "Vicente Fernández", 1987, "Ranchera");
agregar("La Ley Del Monte", "Vicente Fernández", 1978, "Ranchera");
agregar("Que Te Vaya Bonito", "Vicente Fernández", 1978, "Ranchera");
agregar("Cielito Lindo", "Pedro Infante", 1947, "Ranchera");
agregar("Ay Jalisco No Te Rajes", "Jorge Negrete", 1941, "Ranchera");
agregar("México Lindo Y Querido", "Jorge Negrete", 1945, "Ranchera");
agregar("Ella", "José Alfredo Jiménez", 1954, "Ranchera");
agregar("El Hijo Del Pueblo", "José Alfredo Jiménez", 1952, "Ranchera");
agregar("Caminos De Guanajuato", "José Alfredo Jiménez", 1960, "Ranchera");
agregar("Paloma Negra", "Chavela Vargas", 1971, "Ranchera");
agregar("Macorina", "Chavela Vargas", 1994, "Ranchera");
agregar("La Llorona", "Chavela Vargas", 1961, "Ranchera");
agregar("Cucurrucucú Paloma", "Lola Beltrán", 1954, "Ranchera");
agregar("Huapango De Moncayo", "Orquesta Sinfónica", 1941, "Ranchera");
agregar("Cielo Rojo", "Flor Silvestre", 1950, "Ranchera");
agregar("Serenata Huasteca", "José Alfredo Jiménez", 1952, "Ranchera");
agregar("Un Mundo Raro", "José Alfredo Jiménez", 1954, "Ranchera");
agregar("Amanecí En Tus Brazos", "José Alfredo Jiménez", 1956, "Ranchera");
agregar("Te Solté La Rienda", "Antonio Aguilar", 1968, "Ranchera");
agregar("Triste Recuerdo", "Antonio Aguilar", 1965, "Ranchera");
agregar("Caballo Prieto Azabache", "Antonio Aguilar", 1972, "Ranchera");
agregar("Tu Y Las Nubes", "Pedro Infante", 1948, "Ranchera");
agregar("Amarga Navidad", "Pedro Infante", 1952, "Ranchera");
agregar("Las Mañanitas", "Pedro Infante", 1948, "Ranchera");
agregar("Amor Eterno", "Juan Gabriel", 1984, "Ranchera");
agregar("Así Fue", "Juan Gabriel", 1988, "Ranchera");
agregar("No Tengo Dinero", "Juan Gabriel", 1972, "Ranchera");
agregar("Se Me Olvidó Otra Vez", "Juan Gabriel", 1974, "Ranchera");
agregar("Yo No Nací Para Amar", "Juan Gabriel", 1975, "Ranchera");
agregar("Insensible", "Juan Gabriel", 1975, "Ranchera");
agregar("Te Lo Pido Por Favor", "Juan Gabriel", 1986, "Ranchera");
agregar("Pero Qué Necesidad", "Juan Gabriel", 1994, "Ranchera");
agregar("La Diferencia", "Juan Gabriel", 1988, "Ranchera");
agregar("Como Quién Pierde Una Estrella", "Alejandro Fernández", 1996, "Ranchera");
agregar("Nube Viajera", "Alejandro Fernández", 1997, "Ranchera");
agregar("Si Tú Supieras", "Alejandro Fernández", 1997, "Ranchera");
agregar("Mátalas", "Alejandro Fernández", 2003, "Ranchera");
agregar("Hoy Tengo Ganas De Ti", "Alejandro Fernández", 2013, "Ranchera");
agregar("No Me Sé Rajar", "Alejandro Fernández", 1997, "Ranchera");

// REGGAETON (8 -> 60, necesito 52)
agregar("Dile", "Don Omar", 2003, "Reggaeton");
agregar("Dale Don Dale", "Don Omar", 2003, "Reggaeton");
agregar("Reggaetón Lento", "CNCO", 2016, "Reggaeton");
agregar("Bandoleros", "Don Omar & Tego Calderón", 2003, "Reggaeton");
agregar("Pobre Diabla", "Don Omar", 2002, "Reggaeton");
agregar("Conteo", "Don Omar", 2006, "Reggaeton");
agregar("Noche De Entierro", "Daddy Yankee & Wisin & Yandel", 2003, "Reggaeton");
agregar("Mayor Que Yo", "Wisin & Yandel", 2005, "Reggaeton");
agregar("Rakata", "Wisin & Yandel", 2005, "Reggaeton");
agregar("Noche De Sexo", "Wisin & Yandel", 2003, "Reggaeton");
agregar("Abusadora", "Wisin & Yandel", 2005, "Reggaeton");
agregar("Algo Me Gusta De Ti", "Wisin & Yandel", 2012, "Reggaeton");
agregar("Pam Pam", "Wisin & Yandel", 2006, "Reggaeton");
agregar("Llamé Pa' Verte", "Jowell & Randy", 2005, "Reggaeton");
agregar("Shorty", "Jowell & Randy", 2007, "Reggaeton");
agregar("Loco", "Jowell & Randy", 2007, "Reggaeton");
agregar("Caile", "Jowell & Randy", 2016, "Reggaeton");
agregar("La Tortura", "Shakira & Alejandro Sanz", 2005, "Reggaeton");
agregar("Hips Don't Lie", "Shakira", 2006, "Reggaeton");
agregar("Waka Waka", "Shakira", 2010, "Reggaeton");
agregar("Loba", "Shakira", 2009, "Reggaeton");
agregar("Atrévete Te Te", "Calle 13", 2005, "Reggaeton");
agregar("Ojos Color Sol", "Calle 13", 2014, "Reggaeton");
agregar("Baila Morena", "Héctor y Tito", 2001, "Reggaeton");
agregar("Gata Gangster", "Héctor y Tito", 2002, "Reggaeton");
agregar("Rompe", "Daddy Yankee", 2005, "Reggaeton");
agregar("Ella Me Levantó", "Daddy Yankee", 2007, "Reggaeton");
agregar("Descontrol", "Daddy Yankee", 2010, "Reggaeton");
agregar("Limbo", "Daddy Yankee", 2012, "Reggaeton");
agregar("Dura", "Daddy Yankee", 2018, "Reggaeton");
agregar("Con Calma", "Daddy Yankee", 2019, "Reggaeton");
agregar("Pásame La Botella", "Jadiel", 2004, "Reggaeton");
agregar("Dime Si Te Vas Con Él", "Jadiel", 2005, "Reggaeton");
agregar("Pa' Que Retozen", "Tego Calderón", 2003, "Reggaeton");
agregar("Métele Sazón", "Tego Calderón", 2006, "Reggaeton");
agregar("Abaniquéame", "Tego Calderón", 2003, "Reggaeton");
agregar("Saoco", "Wisin", 2022, "Reggaeton");
agregar("Que Viva La Vida", "Wisin", 2013, "Reggaeton");
agregar("Adrenalina", "Wisin", 2014, "Reggaeton");
agregar("Yo Voy", "Zion & Lennox", 2004, "Reggaeton");
agregar("Doncella", "Don Omar", 2006, "Reggaeton");
agregar("Angelito", "Don Omar", 2006, "Reggaeton");
agregar("Taboo", "Don Omar", 2011, "Reggaeton");
agregar("Hasta Abajo", "Don Omar", 2010, "Reggaeton");
agregar("Dutty Love", "Don Omar & Natti Natasha", 2012, "Reggaeton");
agregar("Soledad", "Don Omar", 2003, "Reggaeton");
agregar("Cayo El Sol", "Jowell & Randy", 2010, "Reggaeton");
agregar("Bailando Fue", "Jowell & Randy", 2007, "Reggaeton");
agregar("Te Robaré", "Nicky Jam & Ozuna", 2017, "Reggaeton");
agregar("Travesuras", "Nicky Jam", 2014, "Reggaeton");
agregar("Hasta El Amanecer", "Nicky Jam", 2016, "Reggaeton");
agregar("Si Tú La Ves", "Nicky Jam & Wisin", 2017, "Reggaeton");

// Re-numerar y ordenar
todas.sort((a, b) => a.artista.localeCompare(b.artista) || a.year - b.year);
todas.forEach((c, i) => c.id = String(i + 1));

writeFileSync('./src/data/clasicos.json', JSON.stringify(todas, null, 2), 'utf-8');

const generos = {};
todas.forEach(c => { generos[c.genero] = (generos[c.genero] || 0) + 1; });
console.log(`Total: ${todas.length} canciones`);
console.log('\nPor género:');
Object.entries(generos).sort((a,b) => b[1]-a[1]).forEach(([g, n]) => console.log(`  ${g}: ${n}`));
