import { readFileSync, writeFileSync } from 'fs';

const existentes = JSON.parse(readFileSync('./src/data/clasicos.json', 'utf-8'));

const existentesSet = new Set(existentes.map(c => `${c.titulo.toLowerCase()}|${c.artista.toLowerCase()}`));

function yaExiste(titulo, artista) {
  return existentesSet.has(`${titulo.toLowerCase()}|${artista.toLowerCase()}`);
}

function agregar(titulo, artista, year, genero) {
  const key = `${titulo.toLowerCase()}|${artista.toLowerCase()}`;
  if (existentesSet.has(key)) return;
  existentesSet.add(key);
  nuevas.push({ titulo, artista, year, genero });
}

const nuevas = [];

// LISTA 1
agregar("Que Te Pasa", "Yuri", 1987, "Rock/Pop");
agregar("Quién Como Tú", "Ana Gabriel", 1989, "Balada");
agregar("Ella No Volverá", "Dr. Bellido", 2012, "Reggaeton");
agregar("Cómo Te Extraño Mi Amor", "Café Tacuba", 1992, "Rock/Pop");
agregar("No Te Vayas", "Ráfaga", 1998, "Cumbia");
agregar("Dancing Queen", "ABBA", 1976, "Rock/Pop");
agregar("Puré de Papas", "Cecilia La Incomparable", 1972, "Cumbia");
agregar("El Apagón", "Yuri", 1987, "Rock/Pop");
agregar("El Hombre Que Yo Amo", "Myriam Hernández", 1988, "Balada");
agregar("Yo No Soy Esa Mujer", "Paulina Rubio", 2000, "Rock/Pop");
agregar("Todos Me Miran", "Gloria Trevi", 2006, "Rock/Pop");
agregar("Él Me Mintió", "Amanda Miguel", 1982, "Balada");
agregar("El Noa Noa", "Juan Gabriel", 1980, "Ranchera");
agregar("Te Amaré", "Miguel Bosé", 2004, "Balada");
agregar("Rosas", "La Oreja de Van Gogh", 2003, "Rock/Pop");
agregar("Ni Una Sola Palabra", "Paulina Rubio", 2006, "Rock/Pop");
agregar("Ahora Te Puedes Marchar", "Luis Miguel", 1987, "Rock/Pop");
agregar("Colgando En Tus Manos", "Carlos Baute", 2008, "Balada");
agregar("No Me Doy Por Vencido", "Luis Fonsi", 2008, "Balada");
agregar("Mentía", "Miranda!", 2004, "Rock/Pop");
agregar("Un Siglo Sin Ti", "Chayanne", 2003, "Balada");
agregar("Como Un Lobo", "Miguel Bosé", 2007, "Rock/Pop");
agregar("Desde Que Te Vi", "Natalino", 2010, "Cumbia");
agregar("Y Tú Te Vas", "Chayanne", 1998, "Balada");
agregar("Fuiste Tú", "Ricardo Arjona", 2012, "Balada");
agregar("Aquí Estoy Yo", "Luis Fonsi", 2009, "Balada");
agregar("Si No Te Hubieras Ido", "Marco Antonio Solís", 1997, "Balada");
agregar("Si Nos Quedara Poco Tiempo", "Chayanne", 2014, "Balada");
agregar("Dónde Está El Amor", "Pablo Alborán", 2014, "Balada");
agregar("Cuando Calienta El Sol", "Luis Miguel", 1990, "Ranchera");
agregar("Miénteme Una Vez", "Los Vásquez", 2014, "Cumbia");
agregar("Disparo Al Corazón", "Ricky Martin", 2015, "Rock/Pop");
agregar("Enamorado", "Los Vásquez", 2012, "Cumbia");
agregar("No Me Quería", "Los Vásquez", 2013, "Cumbia");
agregar("La Chica De Humo", "Emmanuel", 1983, "Balada");
agregar("Libre Ya De Amores", "Miguel Bosé", 2014, "Rock/Pop");
agregar("Su Florcita", "Agrupación Marilyn", 2008, "Cumbia");
agregar("Completamente Enamorados", "Chayanne", 2000, "Balada");
agregar("Me Enamoré De Ti", "Chayanne", 2008, "Balada");
agregar("Usted", "Luis Miguel", 2002, "Ranchera");
agregar("Si Me Dices Adiós", "La Noche", 2005, "Cumbia");
agregar("Quiero Ser Más Que Tu Amigo", "Leo Rey", 2010, "Cumbia");
agregar("Y Volar", "La Noche", 2003, "Cumbia");
agregar("Rico y Suave", "La Noche", 2004, "Cumbia");
agregar("Me Gusta Todo De Ti", "Noche de Brujas", 2008, "Cumbia");
agregar("Lástima", "La Noche", 2005, "Cumbia");
agregar("Juana María", "Los Vásquez", 2011, "Cumbia");
agregar("¿Y Qué Pasó?", "Jordan", 2007, "Cumbia");
agregar("La Medallita", "Chico Trujillo", 2001, "Cumbia");
agregar("Soy Feo Pero Rico", "La Combo Tortuga", 2012, "Cumbia");
agregar("Traicionera", "Américo", 2006, "Cumbia");
agregar("Cómo Dejar De Amarte", "Los Charros de Lumaco", 2005, "Cumbia");
agregar("Óyeme", "Noche de Brujas", 2006, "Cumbia");
agregar("Yo Me Enamoré", "Amar Azul", 1998, "Cumbia");
agregar("Sákate 1", "Santaferia", 2013, "Cumbia");
agregar("Tú Me Haces Falta", "Los Vásquez", 2015, "Cumbia");
agregar("Para Dormir Contigo Otra Vez", "Villa Cariño", 2010, "Cumbia");
agregar("La Cosecha De Mujeres", "Chico Trujillo", 2003, "Cumbia");
agregar("Borrachito", "Organización X", 1999, "Cumbia");
agregar("Serenata Cruel", "Villa Cariño", 2012, "Cumbia");
agregar("La Escoba", "Chico Trujillo", 2005, "Cumbia");
agregar("El Gil De Tu Ex", "Santaferia", 2016, "Cumbia");
agregar("Qué Calor", "Pibes Chorros", 2002, "Cumbia");
agregar("Loca", "Chico Trujillo", 2001, "Cumbia");
agregar("Maldito Corazón", "Ráfaga", 2000, "Cumbia");
agregar("Algún Día Volverás", "Santaferia", 2011, "Cumbia");
agregar("Olvídalo", "Los Vásquez", 2013, "Cumbia");
agregar("Qué Más Quisiera Yo", "Los Vásquez", 2014, "Cumbia");
agregar("Mientes", "Camila", 2008, "Balada");
agregar("Me Dediqué A Perderte", "Alejandro Fernández", 2010, "Ranchera");
agregar("Me Enamoré", "Agrupación Marilyn", 2009, "Cumbia");
agregar("Ángel De Pasado", "Natalino", 2012, "Cumbia");
agregar("Ángel Para Un Final", "Los Bunkers", 2003, "Rock/Pop");
agregar("Dueles", "Jesse & Joy", 2016, "Rock/Pop");
agregar("Aléjate De Mí", "Camila", 2007, "Balada");
agregar("Mi Loco Amor De Verano", "Andrés de León", 2005, "Cumbia");
agregar("¡Corre!", "Jesse & Joy", 2011, "Rock/Pop");
agregar("No Te Creas Tan Importante", "Vian Yovi", 2018, "Cumbia");
agregar("Quién Te Dijo Eso", "Luis Fonsi", 2002, "Balada");
agregar("Todo Cambió", "Camila", 2006, "Balada");
agregar("Tu Jardín Con Enanitos", "Melendi", 2008, "Rock/Pop");
agregar("Ecos De Amor", "Jesse & Joy", 2015, "Rock/Pop");
agregar("Con Una Lágrima En La Garganta", "Zalo Reyes", 1978, "Balada");
agregar("Cuando Nos Volvamos A Encontrar", "Carlos Vives", 2014, "Tropical");
agregar("Hoy", "Nicole", 2005, "Rock/Pop");
agregar("Te Amo Con Locura", "Eyci and Cody", 2016, "Cumbia");
agregar("Nena", "Marama", 2016, "Cumbia");
agregar("Mi Persona Favorita", "Río Roma", 2017, "Balada");
agregar("Laura Pausini", "En Cambio No", 2005, "Balada");

// LISTA 2
agregar("Si Te Vas", "Shakira", 1998, "Rock/Pop");
agregar("Mi Historia Entre Tus Dedos", "Gianluca Grignani", 1995, "Balada");
agregar("El Último Adiós", "Paulina Rubio", 2000, "Rock/Pop");
agregar("Así Fue", "Isabel Pantoja", 1988, "Balada");
agregar("Hay Un Límite", "Aleste", 2010, "Rock/Pop");
agregar("Andar Conmigo", "Julieta Venegas", 2006, "Rock/Pop");
agregar("Tu Falta De Querer", "Mon Laferte", 2017, "Rock/Pop");
agregar("No Te Creas Tan Importante", "Damas Gratis", 2000, "Cumbia");
agregar("Amor", "Los Auténticos Decadentes", 2016, "Rock/Pop");
agregar("Antología", "Shakira", 1995, "Rock/Pop");
agregar("Así No Te Amará Jamás", "Amanda Miguel", 1982, "Balada");
agregar("Maldita Primavera", "Yuri", 1984, "Rock/Pop");
agregar("Amiga Mía", "Yuri", 1988, "Balada");
agregar("Hasta Que Te Conocí", "Juan Gabriel", 1986, "Ranchera");
agregar("Te Quedó Grande La Yegua", "Alicia Villarreal", 2000, "Ranchera");
agregar("Si Una Vez", "Selena", 1995, "Cumbia");
agregar("El Sol No Regresa", "La Quinta Estación", 2005, "Rock/Pop");
agregar("No Querías Lastimarme", "Gloria Trevi", 1991, "Rock/Pop");
agregar("Simplemente Amigos", "Ana Gabriel", 1988, "Balada");
agregar("Cómo Te Va Mi Amor", "Grupo Pandora", 1988, "Balada");
agregar("A Esa", "Pimpinela", 1985, "Balada");
agregar("Estaba Escrito", "SOS", 2002, "Rock/Pop");
agregar("Baby One More Time", "Britney Spears", 1999, "Rock/Pop");
agregar("Ojos Así", "Shakira", 1998, "Rock/Pop");
agregar("Festa", "Raffaella Carrà", 1977, "Rock/Pop");
agregar("Ven Conmigo", "Christina Aguilera", 2000, "Rock/Pop");
agregar("Wannabe", "Spice Girls", 1996, "Rock/Pop");
agregar("Barbie Girl", "Aqua", 1997, "Rock/Pop");
agregar("I Want To Break Free", "Queen", 1984, "Rock/Pop");
agregar("Huele A Peligro", "Myriam Hernández", 1990, "Balada");
agregar("Rata De Dos Patas", "Paquita La Del Barrio", 1995, "Ranchera");
agregar("Pasito a Pasito", "Gilda", 1995, "Cumbia");
agregar("Paisaje", "Gilda", 1994, "Cumbia");
agregar("Celos", "Daniela Romo", 1983, "Balada");
agregar("Yo No Te Pido La Luna", "Daniela Romo", 1984, "Balada");
agregar("La De La Mochila Azul", "María José Quintanilla", 2005, "Cumbia");
agregar("Maldito Amor", "Supernova", 2003, "Rock/Pop");
agregar("Mi Primer Amor", "María José Quintanilla", 2008, "Cumbia");
agregar("Corazones", "Ana Torroja", 1997, "Rock/Pop");
agregar("Lo Siento", "Belinda", 2003, "Rock/Pop");
agregar("Vuelve", "Ricky Martin", 1998, "Rock/Pop");
agregar("A Fuego Lento", "Rosana", 1996, "Rock/Pop");
agregar("Volar", "Amango", 2007, "Rock/Pop");
agregar("Olvídame y Pega la Vuelta", "Pimpinela", 1984, "Balada");
agregar("Ya Nada Queda", "Kudai", 2004, "Rock/Pop");
agregar("Ángel", "Belinda", 2003, "Rock/Pop");
agregar("Magdalena", "Amango", 2007, "Rock/Pop");
agregar("Caraluna", "Bacilos", 2002, "Rock/Pop");
agregar("Luz Sin Gravedad", "Belinda", 2006, "Rock/Pop");
agregar("Mi Primer Millón", "Bacilos", 2002, "Rock/Pop");
agregar("Tabaco y Chanel", "Bacilos", 2002, "Rock/Pop");
agregar("Nada Fue Un Error", "Coti", 2005, "Rock/Pop");
agregar("Chica De TV", "Mayonesa", 2003, "Cumbia");
agregar("Son de Amores", "Andy & Lucas", 2002, "Rock/Pop");
agregar("En El Muelle de San Blas", "Maná", 1997, "Rock/Pop");
agregar("Deseos de Cosas Imposibles", "La Oreja de Van Gogh", 2006, "Rock/Pop");
agregar("Agachadita", "Mayonesa", 2003, "Cumbia");
agregar("Yo Te Voy A Amar", "N'Sync", 2000, "Rock/Pop");
agregar("No Voy A Cambiar", "BKN", 2006, "Rock/Pop");
agregar("Piensa En Mi", "Leandro & Leonardo", 1992, "Balada");
agregar("México Lindo y Querido", "María José Quintanilla", 2010, "Ranchera");
agregar("Como Yo Te Amo", "Raphael", 1980, "Balada");
agregar("Por Amarte Así", "Cristian Castro", 1997, "Balada");
agregar("La Chica del Bikini Azul", "Luis Miguel", 1985, "Rock/Pop");
agregar("Abrázame Muy Fuerte", "Juan Gabriel", 2000, "Ranchera");
agregar("Hasta Que Me Olvides", "Luis Miguel", 1993, "Balada");
agregar("Por Debajo De La Mesa", "Luis Miguel", 1997, "Balada");
agregar("Tanto La Quería", "Andy & Lucas", 2002, "Rock/Pop");
agregar("Cuando Nadie Ve", "Morat", 2016, "Rock/Pop");
agregar("Las Avispas", "Juan Luis Guerra", 1990, "Tropical");
agregar("Tú No Eres Para Mi", "Fanny Lu", 2005, "Rock/Pop");
agregar("Usted Se Me Llevó La Vida", "Alexandre Pires", 2000, "Tropical");
agregar("Ámame", "Alexandre Pires", 2000, "Tropical");
agregar("Algo Más", "La Quinta Estación", 2005, "Rock/Pop");
agregar("Tal Vez", "Ricky Martin", 2003, "Balada");
agregar("Mariposa Traicionera", "Maná", 2003, "Rock/Pop");
agregar("Y Cómo Es Él", "Marc Anthony", 2000, "Tropical");
agregar("Quién Te Quiere Como Yo", "Carlos Baute", 2008, "Rock/Pop");
agregar("Malo", "Bebe", 2004, "Rock/Pop");
agregar("Chiquitita Bum Bum", "L'Autentika", 2005, "Cumbia");
agregar("Como Yo Nadie Te Ha Amado", "Bon Jovi / Adrián Barilari", 2006, "Rock/Pop");
agregar("Sin Despertar", "Kudai", 2004, "Rock/Pop");
agregar("Te He Prometido", "Leo Dan", 1968, "Clásicos Latinos");
agregar("Tu Cariño Se Me Va", "Buddy Richard", 1968, "Clásicos Latinos");
agregar("Un Ramito De Violetas", "Zalo Reyes", 1978, "Balada");
agregar("Es La Lluvia Que Cae", "Los Iracundos", 1967, "Clásicos Latinos");
agregar("Mi Prisionera", "Zalo Reyes", 1980, "Balada");
agregar("Cómo Deseo Ser Tu Amor", "Los Galos", 1972, "Clásicos Latinos");
agregar("Muñequita", "Luis Dimas", 1965, "Clásicos Latinos");
agregar("Cómo Te Extraño Mi Amor", "Leo Dan", 1964, "Clásicos Latinos");
agregar("O Quizás Simplemente Le Regale Una Rosa", "Leonardo Favio", 1969, "Trova/Cantautor");
agregar("Ding Dong Estas Cosas del Amor", "Leonardo Favio", 1969, "Clásicos Latinos");
agregar("Y Volveré", "Los Ángeles Negros", 1970, "Clásicos Latinos");
agregar("¿Quieres Ser Mi Amante?", "Camilo Sesto", 1973, "Balada");
agregar("Piel de Ángel", "Camilo Sesto", 1974, "Balada");
agregar("Melina", "Camilo Sesto", 1975, "Balada");
agregar("Me Deshice De Tu Amor", "Lucero", 1989, "Rock/Pop");
agregar("Con Los Ojos Cerrados", "Gloria Trevi", 2004, "Rock/Pop");
agregar("Perfecta", "Miranda!", 2005, "Rock/Pop");
agregar("Pero Me Acuerdo De Ti", "Christina Aguilera", 2000, "Balada");
agregar("Hoy Ya Me Voy", "Kany García", 2007, "Balada");
agregar("Cuidarte El Alma", "Chayanne", 2010, "Balada");
agregar("No Sé Por Qué", "Chayanne", 2003, "Balada");
agregar("Quisiera Ser", "Chayanne", 2000, "Balada");
agregar("Me Pierdo Contigo", "Chayanne", 2014, "Balada");
agregar("Candela", "Chayanne", 1998, "Rock/Pop");
agregar("Yo Te Amo", "Chayanne", 2000, "Balada");
agregar("Infinita Tú", "Chayanne", 2014, "Balada");
agregar("¿A Dónde Vamos A Parar?", "Marco Antonio Solís", 1997, "Balada");
agregar("La Venia Bendita", "Marco Antonio Solís", 2002, "Balada");
agregar("Morenita", "Marco Antonio Solís", 2004, "Balada");
agregar("Amor del Bueno", "Reyli Barba", 2003, "Balada");
agregar("Historia de Taxi", "Ricardo Arjona", 1994, "Balada");
agregar("Costumbres", "Rocío Dúrcal", 1980, "Ranchera");
agregar("Lo Aprendí de Ti", "Ha*Ash", 2013, "Rock/Pop");
agregar("Fue Un Placer Conocerte", "Rocío Dúrcal", 1978, "Ranchera");
agregar("Perdón Perdón", "Ha*Ash", 2013, "Rock/Pop");
agregar("Sé Que Te Vas", "Ha*Ash", 2013, "Rock/Pop");
agregar("Ex De Verdad", "Ha*Ash", 2017, "Rock/Pop");
agregar("Dos Copas De Más", "Ha*Ash", 2013, "Rock/Pop");

// LISTA 3
agregar("Bendita Tu Luz", "Maná", 2002, "Rock/Pop");
agregar("Cuando Pase El Temblor", "Soda Stereo", 1985, "Rock/Pop");
agregar("El Día Que Me Quieras", "Luis Miguel", 1990, "Clásicos Latinos");
agregar("Somos Novios", "Armando Manzanero", 1968, "Clásicos Latinos");
agregar("Toda Una Vida", "Los Panchos", 1945, "Clásicos Latinos");
agregar("Europa", "Carlos Santana", 1976, "Rock/Pop");
agregar("Eres Tú", "Mocedades", 1972, "Balada");
agregar("Mediterráneo", "Joan Manuel Serrat", 1971, "Trova/Cantautor");
agregar("Aquellos Ojos Verdes", "Nat King Cole", 1929, "Clásicos Latinos");
agregar("Alfonsina y El Mar", "Cristina Branco", 1969, "Trova/Cantautor");
agregar("América América", "Nino Bravo", 1973, "Balada");
agregar("Cara De Gitana", "Daniel Magal", 1978, "Rock/Pop");
agregar("Yolanda", "Pablo Milanés", 1982, "Trova/Cantautor");
agregar("Entre El Mar Y Una Estrella", "Thalía", 1997, "Rock/Pop");
agregar("Noche De Ronda", "Los Panchos", 1950, "Clásicos Latinos");
agregar("Canción Del Elegido", "Silvio Rodríguez", 1976, "Trova/Cantautor");
agregar("Lágrimas Negras", "Trío Matamoros", 1930, "Clásicos Latinos");
agregar("La Bamba", "Los Lobos", 1987, "Rock/Pop");
agregar("Solamente Una Vez", "Agustín Lara", 1941, "Clásicos Latinos");
agregar("19 Días y 500 Noches", "Joaquín Sabina", 1999, "Trova/Cantautor");
agregar("Por Amor", "Marco Antonio Solís", 1999, "Balada");
agregar("Ojalá Que Llueva Café", "Juan Luis Guerra", 1990, "Tropical");
agregar("Lobo Hombre En París", "La Unión", 1984, "Rock/Pop");
agregar("La Vida Sigue Igual", "Julio Iglesias", 1968, "Balada");
agregar("El Triste", "José José", 1970, "Balada");
agregar("El Cantante", "Héctor Lavoe", 1977, "Tropical");
agregar("Caballo Viejo", "Simón Díaz", 1980, "Tropical");
agregar("Y Cómo Es Él", "José Luis Perales", 1982, "Balada");
agregar("Latinoamérica", "Calle 13", 2011, "Reggaeton");
agregar("Conciencia", "Gilberto Santa Rosa", 1990, "Tropical");
agregar("Se Fue", "Laura Pausini", 1993, "Balada");
agregar("Periodico De Ayer", "Héctor Lavoe", 1976, "Tropical");
agregar("Mujer Contra Mujer", "Mecano", 1988, "Rock/Pop");
agregar("Solo Le Pido A Dios", "León Gieco", 1978, "Trova/Cantautor");
agregar("Los Momentos", "Eduardo Gatti", 1972, "Trova/Cantautor");
agregar("Te Recuerdo Amanda", "Víctor Jara", 1974, "Trova/Cantautor");
agregar("La Gozadera", "Gente de Zona", 2015, "Tropical");
agregar("Hey!", "Julio Iglesias", 1980, "Balada");
agregar("La Flor De La Canela", "Chabuca Granda", 1950, "Trova/Cantautor");
agregar("Que Nadie Sepa Mi Sufrir", "Julio Jaramillo", 1953, "Clásicos Latinos");
agregar("Somos", "Raphael", 1954, "Clásicos Latinos");
agregar("En Un Rincón Del Alma", "Alberto Cortez", 1966, "Trova/Cantautor");
agregar("Entre Dos Tierras", "Héroes del Silencio", 1990, "Rock/Pop");
agregar("Si Se Calla El Cantor", "Mercedes Sosa", 1977, "Trova/Cantautor");
agregar("Esta Tarde Vi Llover", "Armando Manzanero", 1967, "Clásicos Latinos");
agregar("Ella Ya Me Olvidó", "Leonardo Favio", 1968, "Clásicos Latinos");
agregar("El Reloj", "Lucho Gatica", 1957, "Clásicos Latinos");
agregar("El Gato Que Está Triste Y Azul", "Roberto Carlos", 1973, "Balada");
agregar("Volver", "Carlos Gardel", 1935, "Clásicos Latinos");
agregar("Cucurrucucú Paloma", "Caetano Veloso", 1994, "Clásicos Latinos");
agregar("Piensa En Mi", "Chavela Vargas", 1961, "Clásicos Latinos");
agregar("Fina Estampa", "Chabuca Granda", 1956, "Trova/Cantautor");
agregar("Olvídame y Pega La Vuelta", "Pimpinela", 1984, "Balada");
agregar("Hoy Ya Me Voy", "Kany García", 2007, "Balada");

const todas = [...existentes, ...nuevas.map((c, i) => ({ id: String(existentes.length + i + 1), ...c }))];
todas.sort((a, b) => a.artista.localeCompare(b.artista) || a.year - b.year);

// Re-numerar IDs
todas.forEach((c, i) => c.id = String(i + 1));

writeFileSync('./src/data/clasicos.json', JSON.stringify(todas, null, 2), 'utf-8');

// Conteo
const generos = {};
todas.forEach(c => { generos[c.genero] = (generos[c.genero] || 0) + 1; });
console.log(`Total: ${todas.length} canciones`);
console.log(`Nuevas agregadas: ${nuevas.length}`);
console.log('\nPor género:');
Object.entries(generos).sort((a, b) => b[1] - a[1]).forEach(([g, n]) => console.log(`  ${g}: ${n}`));
